[versions]
agp = "8.5.2"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

